version: '3.8'

services:
  env_edge_gateway_rpi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: env_edge_gateway_rpi
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge